Adding in ability to read merge cells from xls and xlsx files.
tafia/calamine pull request #437
Opened 2024-05-19 13:21 UTC by magackame

Closes #305 based on rebase of #307

2024-05-24 17:22 UTC, tafia commented
Thanks for the PR, I've made a few comments.

2024-05-24 17:44 UTC, tafia requested changes

2024-05-24 17:44 UTC, tafia commented on src/xls.rs
> +    pub fn worksheet_merge_cells(&mut self, name: &str) -> Option<Vec<Dimensions>> {
Why do you need a `&mut` here ?

2024-05-24 17:44 UTC, tafia commented on src/xls.rs
> +    sheets: BTreeMap<String, (Range<Data>, Range<String>, Vec<Dimensions>)>,
At some point we will probably need to have some struct with property names.

2024-05-24 17:44 UTC, tafia commented on src/xls.rs
> +    pub fn worksheet_merge_cells_at(&mut self, n: usize) -> Option<Vec<Dimensions>> {
`&mut` not required here I well I believe.

2024-05-24 17:44 UTC, tafia commented on src/xls.rs
> +        let name = self.sheet_names().get(n)?.to_string();
`to_string` not required.,

2024-05-24 17:44 UTC, tafia commented on src/xlsx/mod.rs
> +    /// Gets the worksheet merge cell demensions
typo

2024-05-24 17:44 UTC, tafia commented on src/xlsx/mod.rs
> +            let mut xml = xml_result.unwrap();
Do not `unwrap`. It can fail and should be handled.
As the closure should return a `Result` anyway, you could use `?`.

2024-05-24 17:44 UTC, tafia commented on src/xlsx/mod.rs
> +        let xml = match self.sheets.iter().find(|&&(ref n, _)| n == name) {
```suggestion
        let (_, path) = self.sheets.iter().find(|&&(ref n, _)| n == name)?;
        let xml_result = xml_reader(&mut self.zip, path)?;
         // ...
         Some(Ok(merged_cells))
```

2024-05-24 17:44 UTC, tafia commented on src/xlsx/mod.rs
> +        let name = self.sheet_names().get(n)?.to_string();
`to_string` unecessary.

2024-05-24 17:44 UTC, tafia commented on src/xlsx/mod.rs
> +                    match a.map_err(XlsxError::XmlAttr)? {
`if let` ...

2024-05-24 17:44 UTC, tafia commented on src/xlsx/mod.rs
> +                            match get_dimension(&v) {
`merge_cells.push(get_dimension(&v)?)`

2024-05-24 17:44 UTC, tafia commented on tests/test.rs
> +macro_rules! merge_cells_eq {
Can you replace by a function? I think it is always the same inputs.

2024-05-24 21:21 UTC, magackame commented on tests/test.rs
> +macro_rules! merge_cells_eq {
Removed completely, we can just compare `Vec`s directly using `assert_eq!`

2024-05-24 21:22 UTC, magackame commented on src/xlsx/mod.rs
> +        let name = self.sheet_names().get(n)?.to_string();
I rewrote this, but `.clone()` is still needed because we can't borrow mutably + immutably from `self`

2024-05-24 21:22 UTC, magackame commented on src/xls.rs
> +    sheets: BTreeMap<String, (Range<Data>, Range<String>, Vec<Dimensions>)>,
Is something like that satisfactory?

```rs
struct SheetData {
    range: Range<Data>,
    formula: Range<String>,
    merge_cells: Vec<Dimensions>,
}
```

Should this be a different PR or just an additional commit here is enough?

2024-05-27 04:42 UTC, tafia approved these changes

2024-05-27 04:42 UTC, merged

2024-05-27 04:42 UTC, tafia commented
Thanks!